version: '3.8'

services:
  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./teste.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "7000:5432"

  java:
    build: ./users-system
    ports:
      - "8081:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - "3000:4200"

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8010:80"

volumes:
  pgdata:
